// Generated by IcedCoffeeScript 1.8.0-d
var postlist, request, setting;

setting = require('./index-setting.json');

request = require('request');

postlist = {
  index: "test",
  type: "test",
  searchvalue: '辅导费'
};

request.post({
  url: "http://192.168.0.132:3000/search",
  form: postlist
}, function(err, httpResponse, body) {
  if (err) {
    return console.log(err);
  } else {
    return console.log(body);
  }
});
